package com.illusion.checkfirm.features.sherlock.util

enum class SherlockStatus {
    INITIAL,
    FAIL,
    RUNNING,
    SUCCESS,
    NO_WARNING,
    WARNING_SCRIPT_START_INVALID,
    WARNING_SCRIPT_END_INVALID,
    WARNING_BUILD_NUMBER_BOOTLOADER,
    WARNING_BUILD_NUMBER_ONE_UI_VERSION,
    WARNING_BUILD_NUMBER_YEAR,
    WARNING_BUILD_NUMBER_MONTH,
    WARNING_BUILD_NUMBER_REVISION
}